### PR TITLE
Add thanks for errors&typos corrections in Russian

### PR DESCRIPTION
**Pull request by eugeneloza**

### CODE REVIEW

**Comment by michaliskambi** [comment]
Thanks!

**Comment by michaliskambi** [comment]
I'll regenerate https://castle-engine.io/modern_pascal_introduction_russian.html later today :) Will let here know.

**Comment by michaliskambi** [comment]
1\. I regenerated output for the Russian version on 

https://castle-engine.io/modern_pascal_introduction_russian.html

https://castle-engine.io/modern_pascal_introduction_russian.pdf

2\. I'm not sure does the bottom of the document look as you'd like. Note that in AsciiDoctor you have


```
Перевод на русский выполнен:
Александр Скворцов и Евгений Лоза
2016-2019
Благодарность за помощь в поиске и исправлении ошибок и очепяток:
vitaly_l и pupsik @ freepascal.ru
```

but the newlines above are interpreted just like space, so the lines are "glued" in HTML and PDF output. AsciiDoctor syntax is here just like HTML and LaTeX, a mere single newline in input doesn't make a newline in output. You can add newlines to make this into a paragraph, or make this a list, e.g. 

```
Перевод на русский выполнен:
* Александр Скворцов и Евгений Лоза, 2016-2019
* Благодарность за помощь в поиске и исправлении ошибок и очепяток: `vitaly_l и pupsik @ freepascal.ru`
```

I don't know the meaning of this text, I'm just guessing :), so this is only a suggestion -- possibly this is OK, possibly you want to format it better.

3\. I also added support for translating AsciiDoctor "labels" (any text generated by AsciiDoctor, like "Table Of Contents"). It seems to work OK, but the Russian translation doesn't contain e.g. "table of contents" translation...

If you want to play with it, you can improve the https://github.com/michaliskambi/modern-pascal-introduction/blob/master/locale/attributes-ru.adoc to add a line like 

```
:toc-title: Table of Contents
```

(see `attributes-en.adoc` for a reference of possible strings, in English).

If you do this, you can also consider submitting a PR to AsciiDoctor, their originals are in this repo: https://github.com/asciidoctor/asciidoctor/tree/master/data/locale .

**Comment by eugeneloza** [comment]
>  You can add newlines to make this into a paragraph, or make this a list, e.g.

Oh, sorry. I've forgotten that. And forgotten to check the output. I'll fix that right away.

The meaning of the text is simple: Thanks to 2 people who spotted the typos in the book :)

> If you want to play with it, you can improve

Thanks, I'll have a look at it.

**Comment by eugeneloza** [comment]
> but the Russian translation doesn't contain e.g. "table of contents" translation...

Hmmm... It does and it works pretty well for me. It's "Содержание" in Russian - it shows correct text in PDF and HTML. Maybe I didn't understand you correctly?

Also, for some reason including `locale/attributes.adoc` doesn't work correctly for me, so I included Russian attributes explicitly. However, the fact that the PDF generated by you is valid, means that something may not be working correctly in my asciidoc 1.5.4 installation.

I've also updated locale attributes, but I kinda got lost in their contribution guidelines... Either those do not apply to translations, or I'm expected to create some sort of tests for the translation files that should fail for old versions.

**Comment by michaliskambi** [comment]
> Hmmm... It does and it works pretty well for me. It's "Содержание" in Russian - it shows correct text in PDF and HTML. Maybe I didn't understand you correctly?

> Also, for some reason including locale/attributes.adoc doesn't work correctly for me, so I included Russian attributes explicitly. However, the fact that the PDF generated by you is valid, means that something may not be working correctly in my asciidoc 1.5.4 installation.

Ah, so it seems that the locale attributes never worked correctly for me, and you just solved why :) That's possibly some problem inside attributes.adoc ( https://github.com/michaliskambi/modern-pascal-introduction/blob/master/locale/attributes.adoc ) , it contains

```
ifdef::lang[include::attributes-{lang}.adoc[]]
```

but it seems that it didn't work (and didn't report any error?). Maybe it needs to include `locale/` subdirectory, if it is resolved with respect to the main xxx.adoc file? In any case, your workaround with just directly referencing `attributes-ru.adoc` makes sense too, after all the Russian sources of AsciiDoc always want the Russian translation :)

You can submit a pull request, and I'll test it in the evening with HTML and PDF on my system:)

**Comment by eugeneloza** [comment]
> `ifdef::lang[include::attributes-{lang}.adoc[]]`

That's the way official asciidoctor documentation says it must work (I've studied this issue). So, my only guess was that Debian repository contained an obsolete version, that didn't support some variables...

However, the fact that it generated table of contents as "Содержание" correctly, means it should have worked for you as expected. Otherwise in Russian text we would have had "Table of Contents", not "Содержание".

**Pull request merged**
