### PR TITLE
Update Russian translation

### PR DESCRIPTION
**Pull request by eugeneloza**
- update locales
- update NOTE command
- fix header to work in 1.5.4 asciidoc version
- minor fixes.

### CODE REVIEW

**Comment by michaliskambi** [comment]
Thank you! I'll rerun AsciiDoctor for HTML + PDF on it later today :)

**Comment by michaliskambi** [comment]
New https://castle-engine.io/modern_pascal_introduction_russian.pdf and https://castle-engine.io/modern_pascal_introduction_russian.html are generated. Now the "Table of Contents" is properly translated in output to "Содержание" (it wasn't in my version generated yesterday), thanks!

**Comment by eugeneloza** [comment]
Thanks a lot! :)

**Comment by michaliskambi** [comment]
@SpanerRh @eugeneloza I made a prominent link to the translations, including Russian, from our website: see 

- https://castle-engine.io/modern_pascal sidebar, 

- and the dedicated translations list on https://castle-engine.io/modern_pascal_translations .

Thank you very much for making the translation!

If you'd like to improve anything in the above pages (e.g. how I credit you on https://castle-engine.io/modern_pascal_translations ) naturally go ahead and ping me. You can just edit this file in cge-www repository: https://github.com/castle-engine/cge-www/blob/master/htdocs/doc/modern_pascal_translations.adoc and submit a pull request.

**Pull request merged**
